/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package Connect4-0.1.0.0 */
#define VERSION_Connect4 "0.1.0.0"
#define MIN_VERSION_Connect4(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)

/* package base-4.9.1.0 */
#define VERSION_base "4.9.1.0"
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  9 || \
  (major1) == 4 && (major2) == 9 && (minor) <= 1)

/* package brick-0.18 */
#define VERSION_brick "0.18"
#define MIN_VERSION_brick(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  18 || \
  (major1) == 0 && (major2) == 18 && (minor) <= 0)

/* package containers-0.5.7.1 */
#define VERSION_containers "0.5.7.1"
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 7)

/* package linear-1.20.7 */
#define VERSION_linear "1.20.7"
#define MIN_VERSION_linear(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  20 || \
  (major1) == 1 && (major2) == 20 && (minor) <= 7)

/* package random-1.1 */
#define VERSION_random "1.1"
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)

/* package vty-5.16 */
#define VERSION_vty "5.16"
#define MIN_VERSION_vty(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  16 || \
  (major1) == 5 && (major2) == 16 && (minor) <= 0)

/* tool gcc-13.0.0 */
#define TOOL_VERSION_gcc "13.0.0"
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  13 || \
  (major1) == 13 && (major2) <  0 || \
  (major1) == 13 && (major2) == 0 && (minor) <= 0)

/* tool ghc-8.0.2 */
#define TOOL_VERSION_ghc "8.0.2"
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  0 || \
  (major1) == 8 && (major2) == 0 && (minor) <= 2)

/* tool ghc-pkg-8.0.2 */
#define TOOL_VERSION_ghc_pkg "8.0.2"
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  0 || \
  (major1) == 8 && (major2) == 0 && (minor) <= 2)

/* tool haddock-2.17.3 */
#define TOOL_VERSION_haddock "2.17.3"
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  17 || \
  (major1) == 2 && (major2) == 17 && (minor) <= 3)

/* tool hpc-0.67 */
#define TOOL_VERSION_hpc "0.67"
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)

/* tool hsc2hs-0.68.1 */
#define TOOL_VERSION_hsc2hs "0.68.1"
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 1)

#define CURRENT_COMPONENT_ID "Connect4-0.1.0.0"

#define CURRENT_PACKAGE_KEY "Connect4-0.1.0.0"


#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
